{
 "title": "Grant Rencher JWT Pizza Service",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average Request Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "serviceLatency_total / 100", "legendFormat": "HTTP latency" },
    {
     "expr": "pizzaCreationLatency_total / 100",
     "legendFormat": "Pizza latency"
    }
   ]
  },
  {
   "title": "HTTP Requests/minute",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(requests_total[1m])", "legendFormat": "{{endpoint}}" }
   ]
  },
  {
   "title": "Revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    { "expr": "rate(totalRevenue_total[1m])", "legendFormat": "Bitcoin/minute" }
   ]
  },
  {
   "title": "Authentications/minute",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(authentication_total[1m])", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Pizza Purchase Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "rate(totalPizzas_total[1m])", "legendFormat": "Pizza purchases/minute" },
    {
     "expr": "rate(totalPizzaFailures_total[1m])",
     "legendFormat": "Purchase failures/minute"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "activeUsers_total", "legendFormat": "Active Users" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memoryPercentage_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "cpuPercentage_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  }
 ]
}